scrape_configs:
  - job_name: nova-scrape
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - "host.docker.internal:5001"
        labels:
          app: nova